Fix two 'out of bounds' bugs
IUPAC-InChI/InChI pull request #72
Opened 2024-12-19 20:13 UTC by chbrown

We (https://patents.google.com/) encountered some data that triggered out of bounds crashes at these array access sites.

SMILES strings that cause problems prior to this fix:
* `CCCCCCCC/C=C\\CCCCCCCC(=O)OCCN(CCOC(=O)CCCCCCC/C=C\\CCCCCCCC)C(=O)CN(C)C.CCCCCCCC/C=C\\CCCCCCCC(=O)OCCN(CCOC(=O)CCCCCCC/C=C\\CCCCCCCC)C(=O)C[N+](C)(C)C.CCCCCCCCCCCCCC(=O)OCCN(CCOC(=O)CCCCCCCCCCCCC)C(=O)CN(C)C.CCCCCCCCCCCCCC(=O)OCCN(CCOC(=O)CCCCCCCCCCCCC)C(=O)C[N+](C)(C)CCO.COS(C)(=O)=O.OCCBr.[3H]N([3H])([3H])([3H])I.[Br-]`
* `C/[AlH2]1=O/[Si@]2(C)O[Si](C)(C)O[Al@H2]3(C)O[Si@@H]4O[AlH2]5(O[Si@]67O[Si@](C)(O1)O[Si@@](C)(O[Si](C)(C)C)O[Al@H2](C)(O6)O[Si@@]1(C)O[Si@]6(C)O[Si@@](C)(O[Si@@]89O[AlH2]%10%11O[Si@]%12%13O[Al](O[Si@@]%14(C)O[Al@@H2]%15(C)O[Si@@](C)(O4)O[SiH-](O5)(O8)O[Si@](C)(O%15)O[Al@@H2](C)(O%12)O%14)O[Si@]4(C)O[Si@@]5(C)O[AlH2]8(C)O[Si]%12(C)O[Si@](C)(O5)O[Al@H2]5(C)O[Si@@]%14(C)O[AlH2]%15(O[Si@@]%16(C)O[Si](C)(C)O[AlH2](C)(C)O[Si@](C)(O%16)O%14)O[Si@](O[Al@@-]%14%16O[Si@@]%17(C)O[Si@](C)(O[Si@@]%18(C)O[Al@@H2]%19(C)O[Si](C)(C)O[Si](C)(C)O[Si@](O%15)(O%19)O[Al@@H2](C)(O%17)O%18)O[Si@@](C)(O%14)O[Al@H2]%14(C)O[Si@@]%15(C)O[Si@](C)(O[Si@@](C)(O%10)O[Al@H2](C)(O%15)O[Si@@](C)(O%11)O[Al@H2](C)(O6)O9)O[Si@@](O%16)(O[Si@@](O8)(O%13)O4)O%14)(O%12)[OH+]5)O[Al@H2](C)(O7)O1)O[Si@](C)(O2)O3.[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+].[Na+]`

Thanks!

2024-12-20 16:26 UTC, nbehrnd commented
@chbrown The InChI executables already can process SMILES as input?  Though discussed multiple times (see e.g., #63), the current development version 1.07.2 (in branch `rwth`, executables for Windows and Linux [here](https://github.com/IUPAC-InChI/InChI/tree/rwth/INCHI-1-BIN), compiled by Dec 9, 2024) ahead of the current stable 1.07.1 (in branch `main`, executables from the [here](https://github.com/IUPAC-InChI/InChI/tree/main/INCHI-1-BIN) and as well as the [releases page](https://github.com/IUPAC-InChI/InChI/releases)) are not able process them (yet).  Instead, the executables anticipate .mol/.sdf files (a [short](https://en.wikipedia.org/wiki/Chemical_table_file#SDF), and an [detailed documentation](https://web.archive.org/web/20210219065450/https://discover.3ds.com/sites/default/files/2020-08/biovia_ctfileformats_2020.pdf)), or InChI strings as input.

2024-12-20 18:22 UTC, chbrown commented
Ah sorry no I was unclear; we mainly use this InChI library via `RDKit`, and in doing so discovered the problematic out-of-bounds accesses arising from this code. We also predominantly pass around SMILES strings so that's why I shared those as examples.

I am not a chemist :/ and am not sure how to replicate the crashes starting from InChIs. 
FWIW, with the attached fix, the SMILES strings above are converted to these InChIs:

* `InChI=1S/C45H85N2O5.C44H82N2O5.C38H75N2O6.C36H70N2O5.C2H5BrO.C2H6O3S.BrH.I.H4N/c1-6-8-10-12-14-16-18-20-22-24-26-28-30-32-34-36-44(49)51-40-38-46(43(48)42-47(3,4)5)39-41-52-45(50)37-35-33-31-29-27-25-23-21-19-17-15-13-11-9-7-2;1-5-7-9-11-13-15-17-19-21-23-25-27-29-31-33-35-43(48)50-39-37-46(42(47)41-45(3)4)38-40-51-44(49)36-34-32-30-28-26-24-22-20-18-16-14-12-10-8-6-2;1-5-7-9-11-13-15-17-19-21-23-25-27-37(43)45-33-29-39(36(42)35-40(3,4)31-32-41)30-34-46-38(44)28-26-24-22-20-18-16-14-12-10-8-6-2;1-5-7-9-11-13-15-17-19-21-23-25-27-35(40)42-31-29-38(34(39)33-37(3)4)30-32-43-36(41)28-26-24-22-20-18-16-14-12-10-8-6-2;3-1-2-4;1-5-6(2,3)4;;;/h20-23H,6-19,24-42H2,1-5H3;19-22H,5-18,23-41H2,1-4H3;41H,5-35H2,1-4H3;5-33H2,1-4H3;4H,1-2H2;1-2H3;1H;;1H4/q+1;;+1;;;;;;/p-1/i;;;;;;;;1T4`
* `InChI=1S/C7H22O27Si11.C5H17O19Si8.2C5H15O8Si4.C4H12O9Si4.2C4H12O6Si3.2CH3O3Si.15CH3.19Al.14Na.34H/c1-35(8,9)25-41(7,26-36(2,10)11)32-44(22,23)34-45(24,33-43(19,20)21)31-40(6,15)29-38(4,13)27-37(3,12)28-39(5,14)30-42(16,17)18;1-26(8,9)19-29(4,13)21-30(5,14)22-31(15,16)24-32(17,20-27(2,10)11)23-28(3,12)18-25(6)7;1-14(2,6)11-16(4,9)13-17(5,10)12-15(3,7)8;1-14(2,3)11-15(4,6)12-16(5,7)13-17(8,9)10;1-14(5,6)11-17(4,12-15(2,7)8)13-16(3,9)10;1-11(2,5)9-13(4,8)10-12(3,6)7;1-11(2,5)9-12(3,4)10-13(6,7)8;2*1-5(2,3)4;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;/h16H,1-7H3;25,32H,1-5H3;2*1-5H3;1-4H3;2*1-4H3;2*1H3;15*1H3;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;/q-16;-13;2*-5;-6;2*-4;2*-3;;;;;;;;;;;;;;;;2*+2;14*+3;3*+4;14*+1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;/t37-,38-,39?,40+,45+;28-,29+,30-;16-,17-;15-,16-;;13-;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;/m0001.1...................................................................................../s1`

But I doubt those will help replicate the bugs :|

I reported similar bugs that arose directly from the RDKit wrapper at https://github.com/rdkit/rdkit/issues/8129 which will be fixed by https://github.com/rdkit/rdkit/pull/8126

2024-12-22 17:38 UTC, nbehrnd commented
The InChI project addresses a problem in chemistry; feature requests, critiques, or contribtions to the code are welcome regardless if its author is a chemist, or not.  For instance, it is possible to query the WIPO database by an InChI i.e., one structure at a time. One InChI working group establishes a way to express [Markush structures](https://en.wikipedia.org/wiki/Markush_structure) seen in patents to eventually describe/search multiple structures at once -- hence potentially useful for patent attorneys.

A couple of additional comments:

- After a copy-paste of the second SMILES string shared by you into [CDKdepict](http://www.simolecule.com/cdkdepict), I question if there is no better way to describe the structure, than a SMILES string.  The visualization contains an unusual trivalent oxygen atom with both a single and a double bond (e.g., lower left hand side) next to a hexavalent aluminum, too -- maybe they contribute to problems in processing this datum.

- More generally speaking (because you mention not to be a chemist), be aware one structure (especially if atoms form a cycle) often can be described with more than one SMILES string.  A recent answer on [chemistry.stackexchange](https://chemistry.stackexchange.com/questions/185973/cycle-two-variants-in-smiles/186008#186008) illustrated this including links to guides by [Daylight](https://www.daylight.com/dayhtml_tutorials/languages/smiles/index.html).  The hint to consolidate SMILES strings if they are from multiple programs/databases e.g., with openbabel and to "sanitize them" (as a check against unusual number of bonds, etc.) with RDKit can equally be useful.

  The answer on stackexchange didn't address _standard_ InChI (InChI starting by `1S/...`) sometimes fail to discern molecules like [2-pyrididone/2-hydroxypyridine](https://en.wikipedia.org/wiki/2-Pyridone) affected by [tautomerism](https://en.wikipedia.org/wiki/Tautomer). In SMILES, 2-pyridone can be described by `C1=CC=CNC(=O)1` with an explicit C=O double bond, its pyridine isomer by `Oc1ccccn1` with an implicit C-O single bond.  For both the standard InChI is `InChI=1S/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)`.  The two become discernible with InChI's optional fixed hydrogen layer to then `InChI=1/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)/f/h7H` (the pyridine form), or `InChI=1/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)/f/h6H` (the pyridone form, both InChI strings generated on the [demo page](https://iupac-inchi.github.io/InChI-Web-Demo/) after disabling the default "mobile H Perception" (note the `f` in the string to indicate this additional layer of information).  This detail can be relevant, e.g. for the description of chemical equilibria.

[2024-12-22_test_case.zip](https://github.com/user-attachments/files/18222694/2024-12-22_test_case.zip)

2024-12-23 22:31 UTC, chbrown commented
Thanks for the added detail! It sounds like what I need to do is separate the layers and ensure that I can replicate the bug starting from an InChI. I will be mostly out of office through the rest of the holidays, so it may be a bit before the next followup.

To clarify one thing though— supposing an InChI is parseable, I take it you are willing to patch execution paths where that InChI may cause your code to segfault, even if said InChI is nonsense or physically impossible?

IIUC, both SMILES strings and InChIs can represent molecules that are physically impossible, or at least implausible, and I suspect the molecules that have tripped me up are just such a case. So if your code is designed with the assumption that input molecules are always physically 'valid', this PR is not the right approach, and I will need to resolve the issue on our end well before we get to the InChI calls.

2024-12-24 00:09 UTC, nbehrnd commented
@chbrown 

> To clarify one thing though— supposing an InChI is parseable, I take it you are willing to patch execution paths where that InChI may cause your code to segfault, even if said InChI is nonsense or physically impossible?

The decision will be up to others (e.g., @gblanke02, @djb-rwth) with close knowledge of the source code, its working, and C.  From chemistry, I got some exposure to Fortran; Python, AWK which are not relevant here.

Many applications (computationally) can process (chemically) questionable or (by current knowledge) plain wrong SMILES strings.  E.g., SMILES string `C#C#C` describes an impossible molecule of five atoms (the ones labeled by 1, 2, and 3 carbon; 4 and 5 hydrogen atoms) because the carbon atom in the center would engage six bonds simultaneously

![wrong](https://github.com/user-attachments/assets/f4316d08-27d0-46be-89d9-9a65dea4aec8)

instead of four (typical maximum for stable compounds like e.g., [methane](https://en.wikipedia.org/wiki/Methane)).  Some GUI based molecule editors (ChemDraw, ChemDoodle, ChemSketch, Marvin, etc) highlight such errors, too.

Still it is possible to generate a .sdf file with some programs and to assign an InChI.  However, the reference executable by InChI trust, and the repackaged version by [DebiChem](https://tracker.debian.org/pkg/inchi) (other Linux distributions [here](https://repology.org/project/inchi/packages)) issue a note to the user back to the command line / the log file written (accessible for grep).  Here 

> `Warning (Accepted unusual valence(s): C(6)) structure #1.`

OpenBabel (as an example of software which implements InChI) for example states

```bash
$ obabel -:"C#C#C" -oinchi
==============================
*** Open Babel Warning  in InChI code
  #1 :Accepted unusual valence(s): C(6)
InChI=1S/C3H2/c1-3-2/h1-2H
1 molecule converted
```

Hence RDKit's rule based approach to check (and if likely necessary) correct SMILES can be useful (especially for large datasets) as an additional safety guard prior to the assignment of InChI.

[2024-12-24_problematic.zip](https://github.com/user-attachments/files/18234178/2024-12-24_problematic.zip)

2025-01-13 13:50 UTC, djb-rwth commented
Closing this pull request with [@nbehrnd's last comment](https://github.com/IUPAC-InChI/InChI/pull/72#issuecomment-2560455407).

2025-03-11 22:27 UTC, wetherbeei commented
@djb-rwth the decision here isn't clear and has security implications for adoption of InChI code in commercial products.

**Will InChI accept modifications to protect against out of bounds, segfault, etc errors from any inchi_Input value, however chemically-invalid it is?** These invalid inputs may come from automated extraction programs or from malicious user inputs, and should not corrupt the memory of the running program. These are the types of errors OSS-Fuzz also aims to expose.

We (patents.google.com) have been impacted by some of the errors @chbrown reported, which cause memory corruption and program crashes for our patent serving and indexing jobs.

2025-03-18 08:50 UTC, djb-rwth commented
Hi @wetherbeei,
I will review the suggested fixes again and give you a feedback soon.

2025-04-12 14:02 UTC, djb-rwth requested changes

2025-04-12 14:02 UTC, djb-rwth commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +                for (m = 0; m < at->valence && m < MAX_NUM_STEREO_ATOM_NEIGH; m++)
This one is fine.

2025-04-12 14:02 UTC, djb-rwth commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +                if (m < at->valence && m < MAX_NUM_STEREO_ATOM_NEIGH)
Also this one.

2025-04-12 14:02 UTC, djb-rwth commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +    for (iso_diff = 0; iso_diff < NUM_H_ISOTOPES; iso_diff++)
This fix would bring significant changes in some `InChI` strings.
Due to some strange reason, it looks as if nearly all `for` loops in `strutil.c` include an additional loop, which means that `=` might have to stay here.
I need to discuss this with the chemists in more detail and will let you know.

2025-04-12 14:02 UTC, djb-rwth commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +    for (iso_diff = 0; iso_diff < NUM_H_ISOTOPES; iso_diff++)
Hi @chbrown and @wetherbeei,
Our chemistry team agreed that the proposed fix cannot be accepted as it involves ammonium as suggested in the comment above.

2025-04-12 14:04 UTC, djb-rwth commented
Hi @chbrown and @wetherbeei,
First two of three suggested fixes can be accepted as commented above.
Please let me know if you would like to remove the third so we can proceed with merging the revised PR.

2025-04-16 18:58 UTC, chbrown commented
Hi thanks for the followup. 

I am confused about the final point; the current behavior allows `iso_diff` to equal `NUM_H_ISOTOPES` (=3) in the final loop, and the 'find isotopic H' branch accesses `num_iso_H[iso_diff]` where `num_iso_H` is defined as an array with fixed length `NUM_H_ISOTOPES` (see `inpdef.h` line 125), so in the case that `iso_diff` == 3, this would be accessing an out of bounds item of `num_iso_H`. Which seems wrong. **Am I missing something?**

I could move the `iso_diff < NUM_H_ISOTOPES` check lower in the code, right before it accesses `num_iso_H[iso_diff]`, but that would have the same effect.

2025-04-16 20:28 UTC, djb-rwth commented
Hi @chbrown,
> Which seems wrong. **Am I missing something?**

No, you are not. 

The issue is rather straightforward, and after I analysed the code in the same way, I still think it is obvious that `<=` should be replaced with `<`.

However, after running some tests on a very specific set of structures, changes in `InChI` string started showing up as a result of this change. I read the whole `strutil.c` script and noticed that there are some strange code tweaks surrounding "explicit H" (hydrogens), e.g. arrays having an extra element such as in: https://github.com/IUPAC-InChI/InChI/blob/27dc8661ca6f15c1cd7bb841d25031de05118e34/INCHI-1-SRC/INCHI_BASE/src/strutil.c#L3933 (although the array in this loop has dimension `4`).

I sent this database and `InChI` output results to the chemistry experts team, and they have just replied that we should not touch this (for now).

The only option now is to speak to them again and ask them to analyse the revised `InChI` strings in order to see if they make any sense from the chemistry viewpoint.

Will be in touch soon.

2025-04-16 20:47 UTC, chbrown commented
As I said before, I'm no chemistry expert, but if it's currently doing (via illegal memory access) what the experts want, the solution might be to fix the array length. I.e., in https://github.com/IUPAC-InChI/InChI/blob/v1.07.3/INCHI-1-SRC/INCHI_BASE/src/inpdef.h#L125:

```patch
-S_CHAR        num_iso_H[NUM_H_ISOTOPES];
+S_CHAR        num_iso_H[NUM_H_ISOTOPES+1];
```

2025-04-16 21:16 UTC, djb-rwth commented
Hi @chbrown,
> As I said before, I'm no chemistry expert, 

Me neither.

> but if it's currently doing (via illegal memory access) what the experts want, the solution might be to fix the array length. I.e., in https://github.com/IUPAC-InChI/InChI/blob/v1.07.3/INCHI-1-SRC/INCHI_BASE/src/inpdef.h#L125:

That is another solution.

Let us see what the chemists will say -- either of these works for me (from a programming standpoint).

2025-04-17 19:17 UTC, djb-rwth commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +    for (iso_diff = 0; iso_diff < NUM_H_ISOTOPES; iso_diff++)
Hi @chbrown,
I gave another look at the whole `strutil.c` script, tested it on the relevant test set and now it all makes sense.
The loop condition __should__ stay `iso_diff <= NUM_H_ISOTOPES` as `num_explicit_H` has dimension of `NUM_H_ISOTOPES + 1` in a function which calls `int DisconnectAmmoniumSalt`.

The only applicable fix for this issue is:

```
...
        else
        {
            /* find isotopic H */
            if ((iso_diff < NUM_H_ISOTOPES) && (at[iN].num_iso_H[iso_diff]))
            {
                at[iN].num_iso_H[iso_diff] --; /* move implicit isotopic H, atw = 1 */
                at[iO].num_iso_H[iso_diff] ++;
                break;
            }
            else
            {
                if (num_explicit_H[iso_diff])
                {
                    nMove_H_iso_diff = iso_diff; /* flag: move explicit isotopic H, atw = 1 */
                    break;
                }
            }
        }
...
```
starting from line https://github.com/IUPAC-InChI/InChI/blob/27dc8661ca6f15c1cd7bb841d25031de05118e34/INCHI-1-SRC/INCHI_BASE/src/strutil.c#L2435 .

2025-04-17 19:17 UTC, djb-rwth commented
Hi @chbrown,
Please read the comment in the review.

2025-04-17 20:01 UTC, chbrown commented on INCHI-1-SRC/INCHI_BASE/src/strutil.c
> +    for (iso_diff = 0; iso_diff < NUM_H_ISOTOPES; iso_diff++)
Ah good point, I hadn't looked deeply at `num_explicit_H` but that kinda makes sense :)

That works for me; force-pushed an update which should do the trick. Thanks!

2025-04-17 20:03 UTC, chbrown commented
Pushed update with your proposal and rebased... should be good now, lmk if not :)

2025-04-17 20:28 UTC, djb-rwth commented
Hi @chbrown,
LGTM -- PR will be merged.
Thanks again!

2025-04-17 20:28 UTC, merged